import AppKit

/// Watches NSPasteboard.
///
/// Polling, because macOS has no clipboard-change notification — every
/// clipboard manager on the platform does exactly this. 200ms is below the
/// threshold where a copy feels like it was missed, and costs nothing: the
/// common case is one integer comparison.
final class ClipboardMonitor {
    /// Markers well-behaved apps put on the pasteboard to say "don't store
    /// this". Respecting them catches password managers, and anything else
    /// that opts in, without needing to know the app.
    /// Marked secret by the source app — password managers set this.
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.agilebits.onepassword",
    ]

    /// Scratch data an app put on the pasteboard for its own use, not for you.
    private static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let pasteboard = NSPasteboard.general
    private let store: Store
    private let blobs: BlobStore
    private let linkPreviews: LinkPreviewService
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Bundle IDs we never capture from, on top of the markers above.
    var blockedBundleIDs: Set<String> = []

    /// Raised while we write to the pasteboard ourselves, so pasting from
    /// ClipBar doesn't feed straight back into the history.
    var ignoreNextChange = false

    var onCapture: ((ClipItem) -> Void)?
    var onChange: (() -> Void)?

    init(store: Store, blobs: BlobStore) {
        self.store = store
        self.blobs = blobs
        self.linkPreviews = LinkPreviewService(store: store, blobs: blobs)
        self.lastChangeCount = pasteboard.changeCount
        self.linkPreviews.onUpdate = { [weak self] in self?.onChange?() }
    }

    func start(interval: TimeInterval = 0.2) {
        stop()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        // .common so the poll keeps running while a menu or resize loop is up.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Capture

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if ignoreNextChange {
            ignoreNextChange = false
            return
        }

        guard shouldCapture() else { return }

        do {
            if let item = try capture() {
                let result = try store.upsert(item)
                if let discarded = result.discardedBlobPath { blobs.delete(discarded) }
                Feedback.captured()
                onCapture?(item)
                onChange?()
                if item.kind == .link,
                   let url = URL(string: item.preview.trimmingCharacters(in: .whitespacesAndNewlines)) {
                    linkPreviews.fetch(itemID: result.id, url: url)
                }
            }
        } catch {
            NSLog("ClipBar: capture failed — \(error)")
        }
    }

    private func shouldCapture() -> Bool {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        if Preferences.ignoreConcealedContent,
           !types.isDisjoint(with: Self.concealedTypes) { return false }
        if Preferences.ignoreTransientContent,
           !types.isDisjoint(with: Self.transientTypes) { return false }

        if let bundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           blockedBundleIDs.contains(bundleID) {
            return false
        }
        return true
    }

    private func capture() throws -> ClipItem? {
        let source = NSWorkspace.shared.frontmostApplication
        let now = Date()

        func item(kind: ClipKind, title: String?, preview: String,
                  fingerprintSource: Data, blobPath: String? = nil, byteSize: Int = 0,
                  linkDomain: String? = nil) throws -> ClipItem {
            ClipItem(
                id: nil,
                kind: kind,
                title: title,
                preview: preview,
                fingerprint: try Crypto.fingerprint(fingerprintSource),
                blobPath: blobPath,
                byteSize: byteSize,
                charCount: preview.count,
                sourceBundleID: source?.bundleIdentifier,
                sourceName: source?.localizedName,
                createdAt: now,
                lastUsedAt: now,
                pinboardID: nil,
                linkDomain: linkDomain
            )
        }

        // Order matters: a copied file also offers a text representation, and
        // the file is the more useful thing to keep.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            let names = urls.map(\.lastPathComponent).joined(separator: ", ")
            let paths = urls.map(\.path).joined(separator: "\n")
            return try item(kind: .file, title: names, preview: paths,
                            fingerprintSource: Data(paths.utf8))
        }

        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            guard let data = pasteboard.data(forType: type) else { continue }
            let image = NSImage(data: data)
            let size = image?.size ?? .zero
            let ext = type == .png ? "png" : "tiff"
            let path = try blobs.write(data, extension: ext)
            let label = "Imagem \(Int(size.width))×\(Int(size.height))"
            return try item(kind: .image, title: label, preview: label,
                            fingerprintSource: data, blobPath: path, byteSize: data.count)
        }

        if let text = pasteboard.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }

            let kind = ClipKind.infer(fromText: trimmed)
            let title = trimmed.split(separator: "\n").first.map(String.init)
            let domain = kind == .link ? URL(string: trimmed)?.host(percentEncoded: false) : nil
            return try item(kind: kind, title: title, preview: text,
                            fingerprintSource: Data(text.utf8), byteSize: text.utf8.count,
                            linkDomain: domain)
        }

        return nil
    }
}
